const bcrypt=require('bcryptjs');
const crypto=require('crypto');
const repo=require('../repositories/technicianRepository');
const whatsapp=require('./whatsappService');
const fs=require('fs/promises'),path=require('path');
const {uploadDir}=require('../../config');

const nextStatus={assigned:'accepted',accepted:'on_the_way',on_the_way:'reached_location',reached_location:'inspection_started',inspection_started:'work_in_progress',work_in_progress:'completed'};
const timestampColumn={accepted:'accepted_at',on_the_way:'travel_started_at',reached_location:'reached_at',inspection_started:'inspection_started_at',work_in_progress:'work_started_at',completed:'work_completed_at'};
const activeStatuses=['accepted','on_the_way','reached_location','inspection_started','work_in_progress'];
function http(message,status=400){return Object.assign(new Error(message),{status});}

async function ownedJob(id,user){const job=await repo.getJob(id,user);if(!job)throw http('Job not found or not assigned to you',404);return job;}
async function navigation(id,user){const job=await ownedJob(id,user),destination=job.gpsLocation;if(!destination)throw http('Customer GPS location is not available for this job',422);const coordinates=`${destination.latitude},${destination.longitude}`;return{jobId:job.id,address:job.address,destination,links:{googleMaps:`https://www.google.com/maps/dir/?api=1&destination=${encodeURIComponent(coordinates)}`,appleMaps:`https://maps.apple.com/?daddr=${encodeURIComponent(coordinates)}`,geo:`geo:0,0?q=${encodeURIComponent(coordinates)}`}};}
async function updateStatus(id,status,notes,user){
  const client=await repo.pool().connect();try{await client.query('BEGIN');const job=await repo.lockOwnedJob(client,id,user);if(!job)throw http('Job not found or not assigned to you',404);
    if(nextStatus[job.status]!==status)throw http(`Invalid transition. Job must move from ${job.status} to ${nextStatus[job.status]||'no further technician status'}`,409);
    if(status==='completed'){
      const counts=await client.query(`SELECT COUNT(*) FILTER(WHERE photo_type='before')::int before,COUNT(*) FILTER(WHERE photo_type='after')::int after FROM job_photos WHERE job_id=$1`,[id]);
      if(!counts.rows[0].before||!counts.rows[0].after)throw http('At least one before and one after photo are required before completing work',422);
    }
    const column=timestampColumn[status];await client.query(`UPDATE technician_jobs SET status=$2,${column}=NOW(),updated_at=NOW() WHERE id=$1`,[id,status]);
    await client.query(`UPDATE service_tickets SET status=$2,updated_at=NOW() WHERE id=$1`,[job.ticket_id,status]);
    await client.query(`INSERT INTO job_status_history(job_id,status,notes,created_by) VALUES($1,$2,$3,$4)`,[id,status,notes,user.id]);
    await client.query(`INSERT INTO audit_logs(user_id,action,entity_type,entity_id,metadata) VALUES($1,'technician.job_status','technician_job',$2,$3::jsonb)`,[user.id,id,JSON.stringify({from:job.status,to:status})]);
    await client.query('COMMIT');
    const events={on_the_way:['service.technician_on_the_way','Technician on the way'],reached_location:['service.technician_reached','Technician reached'],inspection_started:['service.work_started','Work started'],completed:['service.work_completed','Work completed']};
    if(events[status])await require('../../services/notificationService').sendEvent(job.customer_user_id,events[status][0],events[status][1],`Service ${job.ticket_no}: ${status.replaceAll('_',' ')}.`,{ticketNo:job.ticket_no,status});
    if(status==='on_the_way')whatsapp.queueOnTheWay(id).catch(error=>console.error('WhatsApp notification failed',error.message));
    return repo.getJob(id,user);
  }catch(e){await client.query('ROLLBACK');throw e;}finally{client.release();}
}
function validImage(file){const b=file.buffer||Buffer.alloc(0);return file.mimetype==='image/jpeg'&&b[0]===0xff&&b[1]===0xd8&&b[2]===0xff||file.mimetype==='image/png'&&b.subarray(0,8).equals(Buffer.from([137,80,78,71,13,10,26,10]))||file.mimetype==='image/webp'&&b.subarray(0,4).toString()==='RIFF'&&b.subarray(8,12).toString()==='WEBP'||['image/heic','image/heif'].includes(file.mimetype)&&b.subarray(4,8).toString()==='ftyp';}
async function addEvidence(id,files,body,user){await ownedJob(id,user);const evidence={serviceNotes:body.serviceNotes,workDescription:body.workDescription,additionalRemarks:body.additionalRemarks};const notes=Object.fromEntries(Object.entries(evidence).filter(([,v])=>v));if(!files?.length&&!Object.keys(notes).length)throw http('At least one image or evidence note is required',422);if(files?.length&&!body.type)throw http('Photo type is required when uploading images',422);if((files||[]).some(file=>!validImage(file)))throw http('An uploaded file does not match its declared image type',415);const category=body.category||(body.type==='damage'?'damage':body.type==='work'?'work_in_progress':body.type==='after'?'completed_work':null);const photoType=body.type==='damage'?'before':body.type;const client=await repo.pool().connect(),written=[];try{await client.query('BEGIN');for(const file of files||[]){const extension={"image/jpeg":'.jpg',"image/png":'.png',"image/webp":'.webp',"image/heic":'.heic',"image/heif":'.heif'}[file.mimetype],filename=`${Date.now()}-${crypto.randomUUID()}${extension}`;await fs.writeFile(path.join(uploadDir,filename),file.buffer,{flag:'wx'});written.push(filename);await client.query(`INSERT INTO job_photos(job_id,photo_type,photo_category,storage_key,mime_type,uploaded_by) VALUES($1,$2,$3,$4,$5,$6)`,[id,photoType,category,filename,file.mimetype,user.id]);}if(Object.keys(notes).length)await client.query(`UPDATE technician_jobs SET evidence=COALESCE(evidence,'{}'::jsonb)||$2::jsonb,updated_at=NOW() WHERE id=$1`,[id,JSON.stringify(notes)]);await client.query('COMMIT');return repo.getJob(id,user);}catch(e){await client.query('ROLLBACK');await Promise.allSettled(written.map(name=>fs.unlink(path.join(uploadDir,name))));throw e;}finally{client.release();}}
async function addMaterial(id,data,user){const job=await ownedJob(id,user);if(['completed','closed'].includes(job.status))throw http('Materials cannot be changed after work is completed',409);const {rows}=await repo.pool().query(`INSERT INTO job_materials(job_id,name,quantity,unit,notes,created_by) VALUES($1,$2,$3,$4,$5,$6) RETURNING id,name,quantity,unit,notes,created_at AS "createdAt"`,[id,data.name,data.quantity,data.unit,data.notes,user.id]);return rows[0];}
async function shareLocation(id,data,user){const job=await ownedJob(id,user);const {rows:t}=await repo.pool().query('SELECT id,location_sharing FROM technicians WHERE user_id=$1',[user.id]);if(!t[0]?.location_sharing)throw http('Location sharing is disabled in your profile',403);if(!activeStatuses.includes(job.status))throw http('Location can only be shared while the job is active',409);await repo.pool().query(`INSERT INTO job_location_updates(job_id,technician_id,latitude,longitude,accuracy_meters) VALUES($1,$2,$3,$4,$5)`,[id,t[0].id,data.latitude,data.longitude,data.accuracyMeters]);await repo.pool().query(`UPDATE technicians SET last_latitude=$2,last_longitude=$3,last_location_at=NOW() WHERE id=$1`,[t[0].id,data.latitude,data.longitude]);return {shared:true,recordedAt:new Date().toISOString()};}
async function requestCompletionOtp(id,user){const job=await ownedJob(id,user);if(job.status!=='completed')throw http('Finish the work before requesting customer verification',409);const otp=String(crypto.randomInt(100000,1000000));await repo.pool().query('UPDATE job_completion_otps SET consumed_at=NOW() WHERE job_id=$1 AND consumed_at IS NULL',[id]);await repo.pool().query(`INSERT INTO job_completion_otps(job_id,otp_hash,expires_at) VALUES($1,$2,NOW()+INTERVAL '10 minutes')`,[id,await bcrypt.hash(otp,10)]);return {message:'Verification OTP generated for the customer',expiresInSeconds:600,...(process.env.NODE_ENV==='production'?{}:{developmentOtp:otp})};}
async function confirmCompletion(id,data,user){const client=await repo.pool().connect();try{await client.query('BEGIN');const job=await repo.lockOwnedJob(client,id,user);if(!job)throw http('Job not found or not assigned to you',404);if(job.status!=='completed')throw http('Job must be completed before customer verification',409);if(job.customer_confirmation)throw http('Customer confirmation has already been recorded',409);let otpConfirmed=false;if(data.otp){const {rows}=await client.query(`SELECT id,otp_hash FROM job_completion_otps WHERE job_id=$1 AND consumed_at IS NULL AND expires_at>NOW() AND attempts<5 ORDER BY id DESC LIMIT 1`,[id]);if(!rows[0]||!await bcrypt.compare(data.otp,rows[0].otp_hash)){if(rows[0])await client.query('UPDATE job_completion_otps SET attempts=attempts+1 WHERE id=$1',[rows[0].id]);throw http('Invalid or expired customer OTP',422);}await client.query('UPDATE job_completion_otps SET consumed_at=NOW() WHERE id=$1',[rows[0].id]);otpConfirmed=true;}
    const confirmation={otpConfirmed,signatureUrl:data.signatureUrl,accepted:data.accepted,customerName:data.customerName,remarks:data.remarks,confirmedAt:new Date().toISOString()};
    await client.query(`UPDATE technician_jobs SET status='completed',updated_at=NOW(),customer_confirmation=$2::jsonb WHERE id=$1`,[id,JSON.stringify(confirmation)]);await client.query(`UPDATE service_tickets SET status='completed',updated_at=NOW() WHERE id=$1`,[job.ticket_id]);if(job.asset_id)await client.query(`INSERT INTO asset_service_history(asset_id,ticket_id,history_type,notes) SELECT $1,$2,'service',$3 WHERE NOT EXISTS(SELECT 1 FROM asset_service_history WHERE ticket_id=$2 AND history_type='service')`,[job.asset_id,job.ticket_id,data.remarks||'Service completed and customer confirmation recorded']);await client.query(`INSERT INTO audit_logs(user_id,action,entity_type,entity_id,metadata) VALUES($1,'technician.customer_confirmation','technician_job',$2,$3::jsonb)`,[user.id,id,JSON.stringify({method:otpConfirmed?'otp':'signature',accepted:true})]);await client.query('COMMIT');await require('../../services/notificationService').sendEvent(job.customer_user_id,'service.completed','Service completed',`Service ${job.ticket_no} has been completed and confirmed.`,{ticketNo:job.ticket_no,status:'completed'});return repo.getJob(id,user);
  }catch(e){await client.query('ROLLBACK');throw e;}finally{client.release();}}
module.exports={nextStatus,ownedJob,navigation,updateStatus,addEvidence,addMaterial,shareLocation,requestCompletionOtp,confirmCompletion};
