const bcrypt=require('bcryptjs');
const crypto=require('crypto');
const repo=require('../repositories/technicianRepository');
const whatsapp=require('./whatsappService');

const nextStatus={assigned:'accepted',accepted:'on_the_way',on_the_way:'reached_location',reached_location:'inspection_started',inspection_started:'work_in_progress',work_in_progress:'completed'};
const timestampColumn={accepted:'accepted_at',on_the_way:'travel_started_at',reached_location:'reached_at',inspection_started:'inspection_started_at',work_in_progress:'work_started_at',completed:'work_completed_at'};
const activeStatuses=['accepted','on_the_way','reached_location','inspection_started','work_in_progress'];
function http(message,status=400){return Object.assign(new Error(message),{status});}

async function ownedJob(id,user){const job=await repo.getJob(id,user);if(!job)throw http('Job not found or not assigned to you',404);return job;}
async function updateStatus(id,status,notes,user){
  const client=await repo.pool().connect();try{await client.query('BEGIN');const job=await repo.lockOwnedJob(client,id,user);if(!job)throw http('Job not found or not assigned to you',404);
    if(nextStatus[job.status]!==status)throw http(`Invalid transition. Job must move from ${job.status} to ${nextStatus[job.status]||'no further technician status'}`,409);
    if(status==='completed'){
      const counts=await client.query(`SELECT COUNT(*) FILTER(WHERE photo_type='before')::int before,COUNT(*) FILTER(WHERE photo_type='after')::int after FROM job_photos WHERE job_id=$1`,[id]);
      if(!counts.rows[0].before||!counts.rows[0].after)throw http('At least one before and one after photo are required before completing work',422);
    }
    const column=timestampColumn[status];await client.query(`UPDATE technician_jobs SET status=$2,${column}=NOW(),updated_at=NOW() WHERE id=$1`,[id,status]);
    await client.query(`UPDATE service_tickets SET status=$2,updated_at=NOW() WHERE id=$1`,[job.ticket_id,status]);
    await client.query(`INSERT INTO job_status_history(job_id,status,notes,created_by) VALUES($1,$2,$3,$4)`,[id,status,notes,user.id]);
    await client.query(`INSERT INTO audit_logs(user_id,action,entity_type,entity_id,metadata) VALUES($1,'technician.job_status','technician_job',$2,$3::jsonb)`,[user.id,id,JSON.stringify({from:job.status,to:status})]);
    await client.query('COMMIT');
    if(status==='on_the_way')whatsapp.queueOnTheWay(id).catch(error=>console.error('WhatsApp notification failed',error.message));
    return repo.getJob(id,user);
  }catch(e){await client.query('ROLLBACK');throw e;}finally{client.release();}
}
async function addEvidence(id,files,body,user){await ownedJob(id,user);if(!files?.length)throw http('At least one image is required',422);const client=await repo.pool().connect();try{await client.query('BEGIN');for(const file of files)await client.query(`INSERT INTO job_photos(job_id,photo_type,storage_key,mime_type,uploaded_by) VALUES($1,$2,$3,$4,$5)`,[id,body.type,`/uploads/${file.filename}`,file.mimetype,user.id]);const evidence={serviceNotes:body.serviceNotes,workDescription:body.workDescription,additionalRemarks:body.additionalRemarks};await client.query(`UPDATE technician_jobs SET evidence=COALESCE(evidence,'{}'::jsonb)||$2::jsonb,updated_at=NOW() WHERE id=$1`,[id,JSON.stringify(Object.fromEntries(Object.entries(evidence).filter(([,v])=>v)))]);await client.query('COMMIT');return repo.getJob(id,user);}catch(e){await client.query('ROLLBACK');throw e;}finally{client.release();}}
async function addMaterial(id,data,user){const job=await ownedJob(id,user);if(['completed','closed'].includes(job.status))throw http('Materials cannot be changed after work is completed',409);const {rows}=await repo.pool().query(`INSERT INTO job_materials(job_id,name,quantity,unit,notes,created_by) VALUES($1,$2,$3,$4,$5,$6) RETURNING id,name,quantity,unit,notes,created_at AS "createdAt"`,[id,data.name,data.quantity,data.unit,data.notes,user.id]);return rows[0];}
async function shareLocation(id,data,user){const job=await ownedJob(id,user);const {rows:t}=await repo.pool().query('SELECT id,location_sharing FROM technicians WHERE user_id=$1',[user.id]);if(!t[0]?.location_sharing)throw http('Location sharing is disabled in your profile',403);if(!activeStatuses.includes(job.status))throw http('Location can only be shared while the job is active',409);await repo.pool().query(`INSERT INTO job_location_updates(job_id,technician_id,latitude,longitude,accuracy_meters) VALUES($1,$2,$3,$4,$5)`,[id,t[0].id,data.latitude,data.longitude,data.accuracyMeters]);await repo.pool().query(`UPDATE technicians SET last_latitude=$2,last_longitude=$3,last_location_at=NOW() WHERE id=$1`,[t[0].id,data.latitude,data.longitude]);return {shared:true,recordedAt:new Date().toISOString()};}
async function requestCompletionOtp(id,user){const job=await ownedJob(id,user);if(job.status!=='completed')throw http('Finish the work before requesting customer verification',409);const otp=String(crypto.randomInt(100000,1000000));await repo.pool().query('UPDATE job_completion_otps SET consumed_at=NOW() WHERE job_id=$1 AND consumed_at IS NULL',[id]);await repo.pool().query(`INSERT INTO job_completion_otps(job_id,otp_hash,expires_at) VALUES($1,$2,NOW()+INTERVAL '10 minutes')`,[id,await bcrypt.hash(otp,10)]);return {message:'Verification OTP generated for the customer',expiresInSeconds:600,...(process.env.NODE_ENV==='production'?{}:{developmentOtp:otp})};}
async function confirmCompletion(id,data,user){const client=await repo.pool().connect();try{await client.query('BEGIN');const job=await repo.lockOwnedJob(client,id,user);if(!job)throw http('Job not found or not assigned to you',404);if(job.status!=='completed')throw http('Job must be completed before customer verification',409);let otpConfirmed=false;if(data.otp){const {rows}=await client.query(`SELECT id,otp_hash FROM job_completion_otps WHERE job_id=$1 AND consumed_at IS NULL AND expires_at>NOW() AND attempts<5 ORDER BY id DESC LIMIT 1`,[id]);if(!rows[0]||!await bcrypt.compare(data.otp,rows[0].otp_hash)){if(rows[0])await client.query('UPDATE job_completion_otps SET attempts=attempts+1 WHERE id=$1',[rows[0].id]);throw http('Invalid or expired customer OTP',422);}await client.query('UPDATE job_completion_otps SET consumed_at=NOW() WHERE id=$1',[rows[0].id]);otpConfirmed=true;}
    const confirmation={otpConfirmed,signatureUrl:data.signatureUrl,accepted:data.accepted,customerName:data.customerName,remarks:data.remarks,confirmedAt:new Date().toISOString()};
    await client.query(`UPDATE technician_jobs SET status='closed',closed_at=NOW(),updated_at=NOW(),customer_confirmation=$2::jsonb WHERE id=$1`,[id,JSON.stringify(confirmation)]);await client.query(`UPDATE service_tickets SET status='closed',updated_at=NOW() WHERE id=$1`,[job.ticket_id]);await client.query(`INSERT INTO job_status_history(job_id,status,notes,created_by) VALUES($1,'closed',$2,$3)`,[id,data.remarks,user.id]);await client.query('COMMIT');return repo.getJob(id,user);
  }catch(e){await client.query('ROLLBACK');throw e;}finally{client.release();}}
module.exports={nextStatus,ownedJob,updateStatus,addEvidence,addMaterial,shareLocation,requestCompletionOtp,confirmCompletion};
