const router = require('express').Router();
const { z } = require('zod');
const controller = require('../controllers/authController');
const validate = require('../middleware/validate');
const { authenticate } = require('../middleware/auth');
router.post('/login', validate(z.object({ email: z.string().email(), password: z.string().min(6), portal: z.enum(['admin', 'customer', 'technician']).optional() })), controller.login);
router.post('/register',validate(z.object({name:z.string().min(2).max(120),mobile:z.string().min(8).max(20),email:z.string().email(),password:z.string().min(8).max(72),companyName:z.string().min(2).max(160),address:z.string().min(3),city:z.string().min(2),state:z.string().min(2),pincode:z.string().regex(/^\d{5,10}$/)})),controller.register);
router.post('/forgot-password',validate(z.object({identifier:z.string().min(5)})),controller.forgotPassword);
router.post('/verify-otp',validate(z.object({identifier:z.string().min(5),otp:z.string().regex(/^\d{6}$/),purpose:z.enum(['verify_registration','reset_password'])})),controller.verifyOtp);
router.post('/reset-password',validate(z.object({resetToken:z.string().min(10),password:z.string().min(8).max(72)})),controller.resetPassword);
router.get('/me', authenticate, controller.me);
router.post('/logout',authenticate,controller.logout);
module.exports = router;
