const router = require('express').Router();
const { z } = require('zod');
const controller = require('../controllers/authController');
const validate = require('../middleware/validate');
const { authenticate } = require('../middleware/auth');
const rateLimit = require('../middleware/rateLimit');
const authLimiter=rateLimit({windowMs:15*60*1000,max:20});
router.post('/login', authLimiter, validate(z.object({ email: z.string().email(), password: z.string().min(6), portal: z.enum(['admin', 'customer', 'technician']).optional() })), controller.login);
const strongPassword=z.string().min(10).max(72).regex(/[a-z]/,'Lowercase letter required').regex(/[A-Z]/,'Uppercase letter required').regex(/\d/,'Number required').regex(/[^A-Za-z0-9]/,'Special character required');
router.post('/register',validate(z.object({name:z.string().min(2).max(120),mobile:z.string().min(8).max(20),email:z.string().email(),password:strongPassword,companyName:z.string().min(2).max(160),address:z.string().min(3),city:z.string().min(2),state:z.string().min(2),pincode:z.string().regex(/^\d{5,10}$/)})),controller.register);
router.post('/forgot-password',authLimiter,validate(z.object({identifier:z.string().min(5)})),controller.forgotPassword);
router.post('/verify-otp',authLimiter,validate(z.object({identifier:z.string().min(5),otp:z.string().regex(/^\d{6}$/),purpose:z.enum(['verify_registration','reset_password'])})),controller.verifyOtp);
router.post('/reset-password',authLimiter,validate(z.object({resetToken:z.string().min(10),password:strongPassword})),controller.resetPassword);
router.post('/resend-registration-otp',authLimiter,validate(z.object({identifier:z.string().min(5)})),controller.resendRegistrationOtp);
router.get('/me', authenticate, controller.me);
router.post('/change-password',authenticate,validate(z.object({currentPassword:z.string().min(6),newPassword:strongPassword})),controller.changePassword);
router.post('/logout',authenticate,controller.logout);
module.exports = router;
