const router = require('express').Router();
const multer = require('multer');
const { z } = require('zod');
const { uploadDir } = require('../config');
const authRoutes = require('./authRoutes');
const catalogRoutes = require('./catalogRoutes');
const orderRoutes = require('./orderRoutes');
const serviceRoutes = require('./serviceRoutes');
const jobRoutes = require('./jobRoutes');
const calculator = require('../controllers/calculatorController');
const dashboard = require('../controllers/dashboardController');
const misc = require('../controllers/miscController');
const validate = require('../middleware/validate');
const { authenticate, authorize } = require('../middleware/auth');
const upload = multer({ dest: uploadDir, limits: { fileSize: 8 * 1024 * 1024 }, fileFilter: (_, file, cb) => cb(null, /^(image\/|application\/pdf)/.test(file.mimetype)) });

router.get('/health', misc.health);
router.use('/auth', authRoutes);
router.use('/catalog', catalogRoutes);
router.use('/orders', orderRoutes);
router.use('/services', serviceRoutes);
router.use('/jobs', jobRoutes);
router.get('/products', authenticate, (req, res, next) => { req.params.resource = 'products'; require('../controllers/catalogController').list(req, res, next); });
router.post('/calculator', authenticate, validate(z.object({ product: z.string(), length: z.coerce.number().positive(), width: z.coerce.number().positive(), quantity: z.coerce.number().int().positive().default(1), material: z.string().optional(), lighting: z.string().optional(), installation: z.boolean().optional(), transportation: z.boolean().optional(), design: z.boolean().optional(), accessories: z.boolean().optional() })), calculator.calculate);
router.get('/admin/dashboard', authenticate, authorize('super_admin', 'admin', 'sales_manager', 'service_manager', 'technician_manager'), dashboard.dashboard);
router.post('/uploads', authenticate, upload.single('file'), (req, res) => req.file ? res.status(201).json({ url: `/uploads/${req.file.filename}`, kind: req.body.kind }) : res.status(422).json({ error: 'A valid image or PDF is required' }));
router.post('/ai/chat', authenticate, misc.aiChat);
router.get('/reports/:type', authenticate, authorize('super_admin', 'admin'), misc.report);
module.exports = router;
