const router = require('express').Router();
const multer = require('multer');
const crypto = require('crypto');
const path = require('path');
const { z } = require('zod');
const { uploadDir } = require('../config');
const authRoutes = require('./authRoutes');
const catalogRoutes = require('./catalogRoutes');
const orderRoutes = require('./orderRoutes');
const serviceRoutes = require('./serviceRoutes');
const jobRoutes = require('./jobRoutes');
const customerRoutes = require('./customerRoutes');
const quotationRoutes = require('./quotationRoutes');
const technicianRoutes = require('./technicianRoutes');
const calculator = require('../controllers/calculatorController');
const dashboard = require('../controllers/dashboardController');
const misc = require('../controllers/miscController');
const validate = require('../middleware/validate');
const { authenticate, authorize, permit } = require('../middleware/auth');
const allowedUploads = new Map([['image/jpeg','.jpg'],['image/png','.png'],['image/webp','.webp'],['image/gif','.gif'],['application/pdf','.pdf']]);
const upload = multer({ storage:multer.diskStorage({destination:uploadDir,filename:(_,file,cb)=>cb(null,`${crypto.randomUUID()}${allowedUploads.get(file.mimetype)||''}`)}), limits: { fileSize: 8 * 1024 * 1024, files:1 }, fileFilter: (_, file, cb) => cb(null, allowedUploads.has(file.mimetype)) });

router.get('/health', misc.health);
router.use('/auth', authRoutes);
router.use('/catalog', catalogRoutes);
router.use('/orders', orderRoutes);
router.use('/services', serviceRoutes);
router.use('/jobs', jobRoutes);
router.use('/customer', customerRoutes);
router.use('/quotations',quotationRoutes);
router.use('/technician',technicianRoutes);
router.get('/products', authenticate, permit('product.view'), (req, res, next) => { req.params.resource = 'products'; require('../controllers/catalogController').list(req, res, next); });
router.post('/calculator', authenticate, validate(z.object({ product: z.string(), length: z.coerce.number().positive(), width: z.coerce.number().positive(), unit:z.enum(['ft','in','cm','m']).default('ft'), quantity: z.coerce.number().int().positive().default(1), material: z.string().optional(), lighting: z.string().optional(), installation: z.boolean().optional(), transportation: z.boolean().optional(), design: z.boolean().optional(), electricalWork:z.boolean().optional(),mountingStructure:z.boolean().optional(), accessories: z.boolean().optional(),customization:z.boolean().optional(),discount:z.coerce.number().min(0).optional() })), calculator.calculate);
router.get('/admin/dashboard', authenticate, authorize('super_admin', 'admin', 'sales_manager', 'service_manager', 'technician_manager'), dashboard.dashboard);
router.post('/uploads', authenticate, upload.single('file'), (req, res) => req.file ? res.status(201).json({ url: `/api/uploads/${req.file.filename}`, kind: req.body.kind }) : res.status(422).json({ error: 'A valid image or PDF is required' }));
router.get('/uploads/:filename', authenticate, (req,res,next)=>{const filename=path.basename(req.params.filename);if(filename!==req.params.filename)return res.status(400).json({error:'Invalid filename'});res.sendFile(path.join(uploadDir,filename),error=>{if(error&&!res.headersSent)next(Object.assign(error,{status:error.statusCode||404}))});});
router.post('/ai/chat', authenticate, misc.aiChat);
router.get('/reports/:type', authenticate, permit('reports.view'), misc.report);
module.exports = router;
