const router=require('express').Router();
const {z}=require('zod');
const controller=require('../controllers/technicianController');
const schemas=require('../validation/technicianSchemas');
const validate=require('../../middleware/validate');
const upload=require('../middleware/technicianUpload');
const {authenticate,authorize}=require('../../middleware/auth');

const id=z.string().regex(/^\d+$/);
const validateId=(req,res,next)=>{const parsed=id.safeParse(req.params.jobId);if(!parsed.success)return res.status(422).json({error:'Invalid job id'});next();};
const validateEvidence=(req,res,next)=>{const parsed=schemas.evidence.safeParse(req.body);if(!parsed.success)return res.status(422).json({error:'Validation failed',details:parsed.error.flatten().fieldErrors});req.body=parsed.data;next();};
const validateJobQuery=(req,res,next)=>{const parsed=schemas.jobQuery.safeParse(req.query);if(!parsed.success)return res.status(422).json({error:'Validation failed',details:parsed.error.flatten().fieldErrors});req.validatedQuery=parsed.data;next();};
router.use(authenticate,authorize('technician'));
router.get('/dashboard',controller.dashboard);
router.get('/profile',controller.profile);
router.patch('/profile',validate(schemas.profile),controller.updateProfile);
router.get('/jobs',validateJobQuery,controller.listJobs);
router.get('/jobs/:jobId',validateId,controller.getJob);
router.get('/jobs/:jobId/navigation',validateId,controller.navigation);
router.patch('/jobs/:jobId/status',validateId,validate(schemas.statusUpdate),controller.updateStatus);
router.post('/jobs/:jobId/evidence',validateId,upload.array('photos',10),validateEvidence,controller.addEvidence);
router.post('/jobs/:jobId/materials',validateId,validate(schemas.material),controller.addMaterial);
router.post('/jobs/:jobId/location',validateId,validate(schemas.location),controller.shareLocation);
router.post('/jobs/:jobId/completion-otp',validateId,controller.requestOtp);
router.post('/jobs/:jobId/confirm',validateId,validate(schemas.confirmation),controller.confirm);
router.get('/notifications',controller.notifications);
router.patch('/notifications/read-all',controller.readAllNotifications);
router.patch('/notifications/:id/read',controller.readNotification);
router.post('/notifications/devices',validate(z.object({token:z.string().min(20),platform:z.enum(['android','ios','web'])})),controller.registerDevice);
router.delete('/notifications/devices',validate(z.object({token:z.string().min(20)})),controller.unregisterDevice);
router.get('/reviews',controller.reviews);
module.exports=router;
