const db=require('../../database');const pool=()=>db.getPool();
const defaults={company:{name:'SignFix',logoUrl:'',address:'',phone:'',email:'admin@signfix.in',website:'',gstNumber:'',gstLegalName:''},operations:{taxSettings:{gstEnabled:true,defaultRate:18,pricesIncludeTax:false},currency:{code:'INR',symbol:'₹',locale:'en-IN'},notificationSettings:{order:true,quotation:true,payment:true,service:true,technician:true,completion:true,promotion:true},aiSettings:{enabled:true,customerAssistant:true,designDemo:true},pricingSettings:{minimumOrderEnabled:true,allowDiscounts:true,defaultDiscount:0,minimumOrderValue:0,roundFinalAmount:true},orderStatuses:['new','under_review','quotation','approved','production','ready','installation','completed','cancelled'],technicianSettings:{locationTracking:true,completionOtp:true,photoEvidence:true}}};
async function values(){const rows=(await pool().query("SELECT setting_key,value FROM settings WHERE setting_key IN ('company','operations')")).rows.reduce((a,r)=>({...a,[r.setting_key]:r.value}),{});return{company:{...defaults.company,...rows.company},operations:{...defaults.operations,...rows.operations}};}
async function get(req,res){res.json(await values());}async function save(key,value,user){await pool().query('INSERT INTO settings(setting_key,value,updated_at) VALUES($1,$2::jsonb,NOW()) ON CONFLICT(setting_key) DO UPDATE SET value=EXCLUDED.value,updated_at=NOW()',[key,JSON.stringify(value)]);await pool().query('INSERT INTO audit_logs(user_id,action,entity_type,metadata) VALUES($1,$2,$3,$4::jsonb)',[user.id,`settings.${key}.update`,'settings',JSON.stringify({key,changedFields:Object.keys(value)})]);}
async function company(req,res){await save('company',req.body,req.user);res.json(req.body);}async function operations(req,res){await save('operations',req.body,req.user);res.json(req.body);}
async function access(req,res){const [roles,permissions,links]=await Promise.all([pool().query('SELECT id,name FROM roles ORDER BY id'),pool().query('SELECT id,name,description FROM permissions ORDER BY name'),pool().query('SELECT role_id AS "roleId",permission_id AS "permissionId" FROM role_permissions')]);res.json({roles:roles.rows,permissions:permissions.rows,assignments:links.rows});}
async function rolePermissions(req,res){const client=await pool().connect();try{await client.query('BEGIN');const role=(await client.query('SELECT name FROM roles WHERE id=$1',[req.params.id])).rows[0];if(!role)throw Object.assign(new Error('Role not found'),{status:404});if(role.name==='super_admin')throw Object.assign(new Error('Super administrator permissions cannot be reduced'),{status:409});await client.query('DELETE FROM role_permissions WHERE role_id=$1',[req.params.id]);if(req.body.permissionIds.length)await client.query('INSERT INTO role_permissions(role_id,permission_id) SELECT $1,unnest($2::bigint[])',[req.params.id,req.body.permissionIds]);await client.query('INSERT INTO audit_logs(user_id,action,entity_type,entity_id,metadata) VALUES($1,$2,$3,$4,$5::jsonb)',[req.user.id,'role.permissions.update','role',req.params.id,JSON.stringify({permissionIds:req.body.permissionIds})]);await client.query('COMMIT');res.json({roleId:Number(req.params.id),permissionIds:req.body.permissionIds});}catch(e){await client.query('ROLLBACK');throw e;}finally{client.release();}}
async function serviceCategories(req,res){res.json({data:(await pool().query('SELECT id,name,status FROM service_categories ORDER BY name')).rows});}async function createServiceCategory(req,res){const{rows}=await pool().query('INSERT INTO service_categories(name,status) VALUES($1,TRUE) RETURNING id,name,status',[req.body.name]);await pool().query('INSERT INTO audit_logs(user_id,action,entity_type,entity_id,metadata) VALUES($1,$2,$3,$4,$5::jsonb)',[req.user.id,'service_category.create','service_category',rows[0].id,JSON.stringify(req.body)]);res.status(201).json(rows[0]);}async function updateServiceCategory(req,res){const{rows}=await pool().query('UPDATE service_categories SET name=COALESCE($2,name),status=COALESCE($3,status) WHERE id=$1 RETURNING id,name,status',[req.params.id,req.body.name,req.body.status]);if(!rows[0])throw Object.assign(new Error('Service category not found'),{status:404});await pool().query('INSERT INTO audit_logs(user_id,action,entity_type,entity_id,metadata) VALUES($1,$2,$3,$4,$5::jsonb)',[req.user.id,'service_category.update','service_category',rows[0].id,JSON.stringify(req.body)]);res.json(rows[0]);}
module.exports={get,company,operations,access,rolePermissions,serviceCategories,createServiceCategory,updateServiceCategory};
