const { Pool } = require('pg');
const bcrypt = require('bcryptjs');
let pool;
const notifyCustomer=(...args)=>require('./services/notificationService').sendEvent(...args);
function isConfigured() { return Boolean(process.env.DATABASE_URL); }
function getPool() { if (!isConfigured()) throw Object.assign(new Error('DATABASE_URL is required'), { status: 503 }); if (!pool) pool = new Pool({ connectionString: process.env.DATABASE_URL, max: Number(process.env.DB_POOL_SIZE || 10) }); return pool; }
async function health() { await getPool().query('SELECT 1'); return { mode: 'postgres', connected: true }; }
async function findUserByEmail(email) { const { rows } = await getPool().query(`SELECT u.id,u.name,u.email,u.password_hash AS "passwordHash",r.name AS role FROM users u JOIN roles r ON r.id=u.role_id WHERE LOWER(u.email)=$1 AND u.status='active' LIMIT 1`, [email]); return rows[0]; }

const catalog = {
  products: { table: 'products', select: 'id,name,category,description,image_url AS "imageUrl",pricing_method AS "pricingMethod",base_price AS price,status', search: ['name','category','description'], sort: ['id','name','category','base_price','status'] },
  categories: { table: 'product_categories', select: 'id,name,status', search: ['name'], sort: ['id','name','status'] },
  materials: { table: 'materials', select: 'id,name,description,image_url AS "imageUrl",pricing_method AS "pricingMethod",price_per_sqft AS price,status', search: ['name','description'], sort: ['id','name','price_per_sqft','status'] },
  lighting: { table: 'lighting_options', select: 'id,name,description,image_url AS "imageUrl",pricing_method AS "pricingMethod",price_per_sqft AS price,status', search: ['name','description'], sort: ['id','name','price_per_sqft','status'] },
  accessories: { table: 'accessories', select: 'id,name,description,image_url AS "imageUrl",pricing_method AS "pricingMethod",price,status', search: ['name','description'], sort: ['id','name','price','status'] },
  'installation-options': { table: 'installation_options', select: 'id,name,description,image_url AS "imageUrl",pricing_method AS "pricingMethod",price,status', search: ['name','description'], sort: ['id','name','price','status'] },
  'pricing-rules': { table: 'pricing_rules', select: 'id,product_id AS "productId",name,rule_type AS "ruleType",pricing_method AS "pricingMethod",amount,tax_rate AS "taxRate",active AS status', search: ['name','rule_type'], sort: ['id','name','rule_type','amount','active'] },
  'service-categories': { table: 'service_categories', select: 'id,name,status', search: ['name'], sort: ['id','name','status'] },
  customers: { table: 'customer_directory', select: 'id,name,email,mobile,company_name AS company,address,status,created_at AS "createdAt"', search: ['name','email','mobile','company_name'], sort: ['id','name','email','status','created_at'] },
  technicians: { table: 'technician_directory', select: 'id,name,email,mobile,service_areas AS "serviceAreas",status,created_at AS "createdAt"', search: ['name','email','mobile'], sort: ['id','name','status','created_at'] },
  quotations: { table: 'quotation_directory', select: '*', search: ['"quotationNo"','"orderNo"','status'], sort: ['id','"quotationNo"','"orderNo"','"finalAmount"','"validUntil"','status'] },
  assets: { table: 'asset_directory', select: '*', search: ['"assetNo"','customer'], sort: ['id','"assetNo"','customer','"createdAt"'] },
  notifications: { table: 'notification_directory', select: '*', search: ['email','title','body','channel'], sort: ['id','email','channel','"createdAt"'] },
  'notification-templates': { table: 'notification_templates', select: 'id,name,event_key AS "eventKey",title,body,channels,status,updated_at AS "updatedAt"', search: ['name','event_key','title','body'], sort: ['id','name','event_key','status','updated_at'] },
  'ai-leads': { table: 'ai_leads', select: 'id,customer_id AS "customerId",requirement,product,estimated_budget AS "estimatedBudget",contact,metadata,status,created_at AS "createdAt"', search: ['requirement','product','contact','status'], sort: ['id','product','estimated_budget','status','created_at'] },
  'ai-knowledge': { table: 'ai_knowledge_base', select: 'id,title,category,content,status,created_at AS "createdAt"', search: ['title','category','content'], sort: ['id','title','category','status','created_at'] },
  'ai-conversations': { table: 'ai_conversations', select: 'id,user_id AS "userId",question,response,escalation_status AS "escalationStatus",created_at AS "createdAt"', search: ['question','response','escalation_status'], sort: ['id','escalation_status','created_at'] },
  'design-concepts': { table: 'design_concepts', select: 'id,request_id AS "requestId",image_url AS "imageUrl",prompt,status,admin_notes AS "adminNotes",created_at AS "createdAt"', search: ['prompt','status','admin_notes'], sort: ['id','status','created_at'] },
  settings: { table: 'settings', select: 'id,setting_key AS key,value,updated_at AS "updatedAt"', search: ['setting_key'], sort: ['id','setting_key','updated_at'] },
  'audit-logs': { table: 'audit_logs', select: 'id,user_id AS "userId",action,entity_type AS "entityType",entity_id AS "entityId",metadata,created_at AS "createdAt"', search: ['action','entity_type'], sort: ['id','action','entity_type','created_at'] },
  roles: { table: 'roles', select: 'id,name', search: ['name'], sort: ['id','name'] },
  permissions: { table: 'permissions', select: 'id,name,description', search: ['name','description'], sort: ['id','name'] },
};
function resource(name) { const value = catalog[name]; if (!value) throw Object.assign(new Error('Unsupported resource'), { status: 404 }); return value; }
async function listCatalog(name, query = {}) { const item = resource(name); const page = Math.max(1, Number(query.page) || 1), pageSize = Math.min(100, Math.max(5, Number(query.pageSize) || 20)); const params = [], clauses = []; const search = String(query.search || '').trim(); if (search && item.search?.length) { params.push(`%${search}%`); clauses.push(`(${item.search.map(column => `LOWER(COALESCE(${column}::text,'')) LIKE LOWER($1)`).join(' OR ')})`); } if (query.status !== undefined && item.sort?.includes('status')) { params.push(query.status); clauses.push(`status::text=$${params.length}`); } const where = clauses.length ? ` WHERE ${clauses.join(' AND ')}` : ''; const requestedSort = String(query.sort || 'id'), sort = item.sort?.includes(requestedSort) ? requestedSort : 'id'; const direction = String(query.direction).toLowerCase() === 'asc' ? 'ASC' : 'DESC'; const count = await getPool().query(`SELECT COUNT(*)::int total FROM ${item.table}${where}`, params); params.push(pageSize, (page - 1) * pageSize); const { rows } = await getPool().query(`SELECT ${item.select} FROM ${item.table}${where} ORDER BY ${sort} ${direction} LIMIT $${params.length - 1} OFFSET $${params.length}`, params); return { data: rows, page, pageSize, total: count.rows[0].total, totalPages: Math.max(1, Math.ceil(count.rows[0].total / pageSize)) }; }
const writableCatalog = {
  products: { table: 'products', fields: { name: 'name', category: 'category', description: 'description', imageUrl:'image_url', pricingMethod: 'pricing_method', price:'base_price', status: 'status' } },
  categories: { table: 'product_categories', fields: { name: 'name', status: 'status' } },
  materials: { table: 'materials', fields: { name:'name',description:'description',imageUrl:'image_url',pricingMethod:'pricing_method',price:'price_per_sqft',status:'status' } },
  lighting: { table: 'lighting_options', fields: { name:'name',description:'description',imageUrl:'image_url',pricingMethod:'pricing_method',price:'price_per_sqft',status:'status' } },
  accessories: { table: 'accessories', fields: { name:'name',description:'description',imageUrl:'image_url',pricingMethod:'pricing_method',price:'price',status:'status' } },
  'installation-options': { table: 'installation_options', fields: { name:'name',description:'description',imageUrl:'image_url',pricingMethod:'pricing_method',price:'price',status:'status' } },
  'pricing-rules': { table: 'pricing_rules', fields: { productId:'product_id',name:'name',ruleType:'rule_type',pricingMethod:'pricing_method',amount:'amount',taxRate:'tax_rate',status:'active' } },
  'service-categories': { table: 'service_categories', fields: { name: 'name', status: 'status' } },
  'ai-leads': { table: 'ai_leads', fields: { requirement: 'requirement', product: 'product', estimatedBudget: 'estimated_budget', contact: 'contact', status: 'status' } },
  'ai-knowledge': { table: 'ai_knowledge_base', fields: { title: 'title', category: 'category', content: 'content', status: 'status' } },
  'design-concepts': { table: 'design_concepts', fields: { status: 'status', adminNotes: 'admin_notes' } },
  'notification-templates': { table:'notification_templates', fields:{name:'name',eventKey:'event_key',title:'title',body:'body',channels:'channels',status:'status'} },
  settings: { table: 'settings', fields: { key: 'setting_key', value: 'value' } },
};
function writable(name) { const item = writableCatalog[name]; if (!item) throw Object.assign(new Error('This resource is read-only or unsupported'), { status: 422 }); return item; }
async function createCatalog(name, data, user) { const item = writable(name), entries = Object.entries(data).filter(([key, value]) => item.fields[key] && value !== undefined); if (!entries.length) throw Object.assign(new Error('No supported fields supplied'), { status: 422 }); const columns = entries.map(([key]) => item.fields[key]), values = entries.map(([, value]) => value), placeholders = values.map((_, index) => `$${index + 1}`); const { rows } = await getPool().query(`INSERT INTO ${item.table}(${columns.join(',')}) VALUES(${placeholders.join(',')}) RETURNING *`, values); await audit(user.id, `${name}.create`, name, rows[0].id, data); return rows[0]; }
async function updateCatalog(name, id, data, user) { const item = writable(name), entries = Object.entries(data).filter(([key, value]) => item.fields[key] && value !== undefined); if (!entries.length) throw Object.assign(new Error('No supported fields supplied'), { status: 422 }); const values = entries.map(([, value]) => value), sets = entries.map(([key], index) => `${item.fields[key]}=$${index + 1}`); values.push(id); const { rows } = await getPool().query(`UPDATE ${item.table} SET ${sets.join(',')} WHERE id=$${values.length} RETURNING *`, values); if (!rows[0]) throw Object.assign(new Error('Resource not found'), { status: 404 }); await audit(user.id, `${name}.update`, name, id, data); return rows[0]; }
async function deleteCatalog(name, id, user) { const item = writable(name); const hasStatus = Object.values(item.fields).includes('status'); const result = hasStatus ? await getPool().query(`UPDATE ${item.table} SET status=FALSE WHERE id=$1`, [id]) : await getPool().query(`DELETE FROM ${item.table} WHERE id=$1`, [id]); if (!result.rowCount) throw Object.assign(new Error('Resource not found'), { status: 404 }); await audit(user.id, `${name}.${hasStatus ? 'disable' : 'delete'}`, name, id, {}); }

async function listOrders(user,query={}) { const params=[],clauses=[];if(user.role==='customer'){params.push(user.email);clauses.push(`u.email=$${params.length}`);}if(query.status){params.push(query.status);clauses.push(`o.status=$${params.length}`);}if(query.search){params.push(`%${query.search}%`);clauses.push(`(o.order_no ILIKE $${params.length} OR u.name ILIKE $${params.length} OR COALESCE(o.specifications->>'product','') ILIKE $${params.length})`);}const where=clauses.length?`WHERE ${clauses.join(' AND ')}`:'';const {rows}=await getPool().query(`SELECT o.order_no AS id,u.name AS customer,o.specifications,o.estimated_price AS "estimatedPrice",o.status,o.created_at AS "createdAt",u.email AS "createdBy" FROM orders o JOIN customers c ON c.id=o.customer_id JOIN users u ON u.id=c.user_id ${where} ORDER BY o.created_at DESC LIMIT 100`,params);return rows.map(row=>({...row,...(row.specifications||{})}));}
async function createOrder(user, data, orderNo) { const { rows: customers } = await getPool().query('SELECT c.id,c.user_id FROM customers c JOIN users u ON u.id=c.user_id WHERE u.email=$1 LIMIT 1', [user.email]); let customerId = customers[0]?.id, userId=customers[0]?.user_id; if (!customerId && ['super_admin','admin'].includes(user.role)) {const fallback=(await getPool().query('SELECT id,user_id FROM customers ORDER BY id LIMIT 1')).rows[0];customerId=fallback?.id;userId=fallback?.user_id;} if (!customerId) throw Object.assign(new Error('Customer profile not found'), { status: 422 }); const area=data.priceBreakdown?.area??Number(data.length)*Number(data.width)*Number(data.quantity||1);const { rows } = await getPool().query(`INSERT INTO orders(order_no,customer_id,specifications,estimated_price,status) VALUES($1,$2,$3::jsonb,$4,'under_review') RETURNING created_at`, [orderNo, customerId, JSON.stringify({...data,area,areaUnit:data.priceBreakdown?.areaUnit||'sqft',priceLabel:'Estimated Price',priceNotice:'Final quotation may change after Admin review/measurement.'}), data.estimatedPrice || 0]); await notifyCustomer(userId,'order.submitted','Order submitted',`Order ${orderNo} has been submitted.`,{orderNo}); return { ...data, area,areaUnit:data.priceBreakdown?.areaUnit||'sqft', id: orderNo, status: 'under_review', priceLabel:'Estimated Price',priceNotice:'Final quotation may change after Admin review/measurement.',createdAt: rows[0].created_at }; }
async function updateOrderStatus(orderNo, status, user) { const { rows } = await getPool().query('UPDATE orders o SET status=$2,updated_at=NOW() FROM customers c WHERE o.customer_id=c.id AND o.order_no=$1 RETURNING o.order_no AS id,o.status,c.user_id', [orderNo, status]); if (!rows[0]) throw Object.assign(new Error('Order not found'), { status: 404 }); const events={approved:['order.approved','Order approved'],production:['order.production_started','Production started'],production_started:['order.production_started','Production started'],ready:['order.ready','Order ready']};if(events[status])await notifyCustomer(rows[0].user_id,events[status][0],events[status][1],`Order ${orderNo}: ${status.replaceAll('_',' ')}`,{orderNo,status});delete rows[0].user_id;await audit(user.id, 'order.status', 'order', null, { orderNo, status }); return rows[0]; }
async function getOrder(orderNo,user){const params=[orderNo],customerClause=user.role==='customer'?(params.push(user.email),`AND u.email=$2`):'';const order=(await getPool().query(`SELECT o.id AS "databaseId",o.order_no AS id,u.name AS customer,u.email,o.specifications,o.estimated_price AS "estimatedPrice",o.status,o.admin_notes AS "adminNotes",o.installation_technician_id AS "technicianId",o.created_at AS "createdAt",tu.name AS "technicianName" FROM orders o JOIN customers c ON c.id=o.customer_id JOIN users u ON u.id=c.user_id LEFT JOIN technicians t ON t.id=o.installation_technician_id LEFT JOIN users tu ON tu.id=t.user_id WHERE o.order_no=$1 ${customerClause}`,params)).rows[0];if(!order)throw Object.assign(new Error('Order not found'),{status:404});const [quotations,designs,technicians]=await Promise.all([getPool().query('SELECT q.quotation_no AS "quotationNo",q.status,q.final_amount AS "finalAmount",q.valid_until AS "validUntil" FROM quotations q WHERE q.order_id=$1 ORDER BY q.id DESC',[order.databaseId]),getPool().query(`SELECT d.id,d.requirements,d.status,d.created_at AS "createdAt" FROM design_requests d WHERE d.order_id=$1 ORDER BY d.id DESC`,[order.databaseId]),getPool().query("SELECT t.id,u.name,u.mobile FROM technicians t JOIN users u ON u.id=t.user_id WHERE u.status='active' ORDER BY u.name")]);return {...order,...order.specifications,quotations:quotations.rows,designs:designs.rows,technicians:technicians.rows};}
async function updateOrder(orderNo,data,user){const current=await getOrder(orderNo,user);const specs=data.specifications?{...current.specifications,...data.specifications}:null;const {rows}=await getPool().query('UPDATE orders o SET specifications=COALESCE($2::jsonb,specifications),admin_notes=COALESCE($3,admin_notes),installation_technician_id=COALESCE($4,installation_technician_id),status=COALESCE($5,status),updated_at=NOW() FROM customers c WHERE o.customer_id=c.id AND o.order_no=$1 RETURNING o.order_no AS id,o.status,c.user_id',[orderNo,specs?JSON.stringify(specs):null,data.adminNotes,data.technicianId,data.status]);if(!rows[0])throw Object.assign(new Error('Order not found'),{status:404});await getPool().query("INSERT INTO notifications(user_id,channel,title,body) VALUES($1,'push','Order updated',$2)",[rows[0].user_id,`Order ${orderNo} has been updated.`]);await audit(user.id,'order.update','order',current.databaseId,data);return getOrder(orderNo,user);}
async function listServices(user) { const params = []; let where = ''; if (user.role === 'customer') { where = 'WHERE u.email=$1'; params.push(user.email); } const { rows } = await getPool().query(`SELECT s.ticket_no AS id,u.name AS customer,s.category,s.description,s.location,s.photos,s.priority,s.status,s.created_at AS "createdAt",u.email AS "createdBy" FROM service_tickets s JOIN customers c ON c.id=s.customer_id JOIN users u ON u.id=c.user_id ${where} ORDER BY s.created_at DESC LIMIT 100`, params); return rows; }
async function createService(user, data, ticketNo) { const { rows: customers } = await getPool().query('SELECT c.id,c.user_id FROM customers c JOIN users u ON u.id=c.user_id WHERE u.email=$1 LIMIT 1', [user.email]); let customerId = customers[0]?.id,userId=customers[0]?.user_id; if (!customerId && ['super_admin','admin'].includes(user.role)){const fallback=(await getPool().query('SELECT id,user_id FROM customers ORDER BY id LIMIT 1')).rows[0];customerId=fallback?.id;userId=fallback?.user_id;} if (!customerId) throw Object.assign(new Error('Customer profile not found'), { status: 422 });const categoryActive=(await getPool().query('SELECT 1 FROM service_categories WHERE name=$1 AND status=TRUE',[data.category])).rowCount;if(!categoryActive)throw Object.assign(new Error('Active service problem category not found'),{status:422}); const { rows } = await getPool().query(`INSERT INTO service_tickets(ticket_no,customer_id,category,description,location,photos,priority,status) VALUES($1,$2,$3,$4,$5::jsonb,$6::jsonb,$7,'submitted') RETURNING created_at`, [ticketNo, customerId, data.category, data.description, JSON.stringify({ address: data.address, latitude: data.latitude, longitude: data.longitude }), JSON.stringify(data.photos || []), data.priority]);await getPool().query("INSERT INTO notifications(user_id,channel,title,body) VALUES($1,'push','Service request submitted',$2)",[userId,`Service request ${ticketNo} has been submitted.`]); return { ...data, id: ticketNo, status: 'submitted', createdAt: rows[0].created_at, message: 'Your service request has been submitted.' }; }
async function updateService(ticketNo, data, user) { const { rows } = await getPool().query('UPDATE service_tickets s SET status=COALESCE($2,status),priority=COALESCE($3,priority),updated_at=NOW() FROM customers c WHERE s.customer_id=c.id AND s.ticket_no=$1 RETURNING s.ticket_no AS id,s.status,s.priority,c.user_id', [ticketNo, data.status, data.priority]); if (!rows[0]) throw Object.assign(new Error('Service ticket not found'), { status: 404 });const titles={technician_assigned:'Technician assigned',completed:'Service completed',closed:'Service completed'};if(titles[data.status])await getPool().query("INSERT INTO notifications(user_id,channel,title,body) VALUES($1,'push',$2,$3)",[rows[0].user_id,titles[data.status],`Service ${ticketNo}: ${data.status.replaceAll('_',' ')}`]);delete rows[0].user_id; await audit(user.id, 'service.update', 'service_ticket', null, { ticketNo, ...data }); return rows[0]; }
async function listJobs(user) { const params = []; let where = ''; if (user.role === 'technician') { where = 'WHERE tu.email=$1'; params.push(user.email); } const { rows } = await getPool().query(`SELECT j.id,s.ticket_no AS "ticketId",cu.name AS customer,s.category,s.priority,j.status,s.location,tu.name AS technician,j.scheduled_at AS "scheduledAt" FROM technician_jobs j JOIN service_tickets s ON s.id=j.ticket_id JOIN customers c ON c.id=s.customer_id JOIN users cu ON cu.id=c.user_id LEFT JOIN technicians t ON t.id=j.technician_id LEFT JOIN users tu ON tu.id=t.user_id ${where} ORDER BY j.scheduled_at NULLS LAST,j.id DESC`, params); return rows; }
async function updateJobStatus(id, data, user) { const transitions = { assigned: 'accepted', accepted: 'on_the_way', on_the_way: 'reached_location', reached_location: 'inspection_started', inspection_started: 'work_in_progress', work_in_progress: 'completed' }; const current = (await getPool().query('SELECT status FROM technician_jobs WHERE id=$1', [id])).rows[0]; if (!current) throw Object.assign(new Error('Job not found'), { status: 404 }); if (transitions[current.status] !== data.status) throw Object.assign(new Error(`Job must move from ${current.status} to ${transitions[current.status]}`), { status: 409 }); if (data.status === 'completed' && !/^\d{4,6}$/.test(data.customerOtp || '')) throw Object.assign(new Error('Valid customer OTP required'), { status: 422 }); const { rows } = await getPool().query('UPDATE technician_jobs SET status=$2,customer_confirmation=COALESCE($3::jsonb,customer_confirmation) WHERE id=$1 RETURNING *', [id, data.status, data.customerOtp ? JSON.stringify({ otpConfirmed: true }) : null]); await getPool().query('UPDATE service_tickets SET status=$2,updated_at=NOW() WHERE id=(SELECT ticket_id FROM technician_jobs WHERE id=$1)',[id,data.status]);await getPool().query('INSERT INTO job_status_history(job_id,status,notes,created_by) VALUES($1,$2,$3,$4)', [id, data.status, data.notes, user.id]);const target=(await getPool().query('SELECT c.user_id,s.ticket_no FROM technician_jobs j JOIN service_tickets s ON s.id=j.ticket_id JOIN customers c ON c.id=s.customer_id WHERE j.id=$1',[id])).rows[0],events={on_the_way:['service.technician_on_the_way','Technician on the way'],reached_location:['service.technician_reached','Technician reached'],inspection_started:['service.work_started','Work started'],completed:['service.work_completed','Work completed']};if(target&&events[data.status])await notifyCustomer(target.user_id,events[data.status][0],events[data.status][1],`Service ${target.ticket_no}: ${data.status.replaceAll('_',' ')}`,{ticketNo:target.ticket_no,status:data.status});return rows[0]; }
async function calculatePrice(data) {
  const configured=(await getPool().query(`SELECT rule_type,amount FROM pricing_rules WHERE product_id IS NULL AND active`)).rows.reduce((all,row)=>({...all,[row.rule_type]:Number(row.amount)}),{});
  const product=(await getPool().query(`SELECT p.pricing_method,COALESCE((SELECT amount FROM pricing_rules WHERE product_id=p.id AND active ORDER BY id DESC LIMIT 1),NULLIF(p.base_price,0),$2) rate FROM products p WHERE p.name=$1 AND p.status=TRUE`,[data.product,configured.base||0])).rows[0];
  if(!product) throw Object.assign(new Error('Active sign board type not found'),{status:422});
  const material=(await getPool().query('SELECT price_per_sqft price,pricing_method FROM materials WHERE name=$1 AND status=TRUE',[data.material||''])).rows[0];
  const lighting=(await getPool().query('SELECT price_per_sqft price,pricing_method FROM lighting_options WHERE name=$1 AND status=TRUE',[data.lighting||''])).rows[0];
  if(data.material&&!material)throw Object.assign(new Error('Active material not found'),{status:422});
  if(data.lighting&&!lighting)throw Object.assign(new Error('Active lighting option not found'),{status:422});
  const optionPrice=async(table,value,fallback)=>{if(!value)return 0;if(typeof value==='string')return Number((await getPool().query(`SELECT price FROM ${table} WHERE name=$1 AND status=TRUE`,[value])).rows[0]?.price||0);return Number(fallback||0);};
  const factors={ft:1,in:1/12,cm:0.0328084,m:3.28084},quantity=Number(data.quantity),area=data.length*factors[data.unit||'ft']*data.width*factors[data.unit||'ft']*quantity;
  const cost=(rate,method)=>Number(rate||0)*(method==='unit'?quantity:method==='fixed'?1:area);
  const productCost=cost(product.rate,product.pricing_method),materialCost=cost(material?.price??configured.material,material?.pricing_method||'sqft'),lightingCost=cost(lighting?.price??configured.lighting,lighting?.pricing_method||'sqft');
  const installation=await optionPrice('installation_options',data.installation,configured.installation),accessories=await optionPrice('accessories',data.accessories,configured.accessories);
  const transportation=data.transportation?Number(configured.transportation||0):0,design=data.design?Number(configured.design||0):0,electricalWork=data.electricalWork?Number(configured.electricalWork||0):0,mountingStructure=data.mountingStructure?Number(configured.mountingStructure||0):0,customization=data.customization?Number(configured.customization||0):0;
  const gross=productCost+materialCost+lightingCost+installation+transportation+design+electricalWork+mountingStructure+accessories+customization,discount=Math.min(Number(data.discount??configured.discount??0),gross),subtotal=Math.max(Number(configured.minimum||0),gross-discount),gst=Math.round(subtotal*Number(configured.gst||0)/100);
  return {area:Number(area.toFixed(2)),areaUnit:'sqft',productCost,materialCost,lightingCost,installation,transportation,design,electricalWork,mountingStructure,accessories,customization,discount,gst,estimatedPrice:Math.round(subtotal+gst),label:'Estimated Price',notice:'Final quotation may change after Admin review/measurement.'};
}

async function listAdminCustomers(query={}) { return listCatalog('customers',query); }
async function createAdminCustomer(data,user) { const client=await getPool().connect();try{await client.query('BEGIN');const role=(await client.query("SELECT id FROM roles WHERE name='customer' LIMIT 1")).rows[0];if(!role)throw Object.assign(new Error('Customer role is not configured'),{status:422});const passwordHash=await bcrypt.hash(data.password||`SignFix@${Date.now()}`,10);const created=(await client.query('INSERT INTO users(role_id,name,email,mobile,password_hash,status) VALUES($1,$2,LOWER($3),$4,$5,$6) RETURNING id,name,email,mobile,status,created_at AS "createdAt"',[role.id,data.name,data.email,data.mobile||null,passwordHash,data.status||'active'])).rows[0];const customer=(await client.query('INSERT INTO customers(user_id,company_name,payments_enabled) VALUES($1,$2,$3) RETURNING id,company_name AS company,"payments_enabled" AS "paymentsEnabled"',[created.id,data.companyName||null,Boolean(data.paymentsEnabled)])).rows[0];await client.query('COMMIT');await audit(user.id,'customer.create','customer',customer.id,{email:data.email});return {...created,...customer};}catch(error){await client.query('ROLLBACK');if(error.code==='23505')throw Object.assign(new Error('A customer with this email already exists'),{status:409});throw error;}finally{client.release();} }
async function getAdminCustomer(id) { const base=(await getPool().query('SELECT c.id,c.user_id AS "userId",u.name,u.email,u.mobile,u.status,u.created_at AS "createdAt",c.company_name AS company,c.payments_enabled AS "paymentsEnabled" FROM customers c JOIN users u ON u.id=c.user_id WHERE c.id=$1',[id])).rows[0];if(!base)throw Object.assign(new Error('Customer not found'),{status:404});const [addresses,orders,quotations,services,payments,conversations]=await Promise.all([getPool().query('SELECT id,label,address_line AS "addressLine",city,state,pincode,is_default AS "isDefault" FROM customer_addresses WHERE customer_id=$1 ORDER BY is_default DESC,id',[id]),getPool().query('SELECT order_no AS "orderNo",estimated_price AS "estimatedPrice",status,created_at AS "createdAt" FROM orders WHERE customer_id=$1 ORDER BY created_at DESC',[id]),getPool().query('SELECT q.quotation_no AS "quotationNo",q.final_amount AS "finalAmount",q.status,q.valid_until AS "validUntil" FROM quotations q JOIN orders o ON o.id=q.order_id WHERE o.customer_id=$1 ORDER BY q.id DESC',[id]),getPool().query('SELECT ticket_no AS "ticketNo",category,description,status,created_at AS "createdAt" FROM service_tickets WHERE customer_id=$1 ORDER BY created_at DESC',[id]),getPool().query('SELECT p.id,p.amount,p.status,p.reference,p.created_at AS "createdAt" FROM payments p JOIN quotations q ON q.id=p.quotation_id JOIN orders o ON o.id=q.order_id WHERE o.customer_id=$1 ORDER BY p.id DESC',[id]),getPool().query('SELECT id,question,response,escalation_status AS "escalationStatus",created_at AS "createdAt" FROM ai_conversations WHERE user_id=$1 ORDER BY created_at DESC',[base.userId])]);return {...base,addresses:addresses.rows,orders:orders.rows,quotations:quotations.rows,services:services.rows,payments:base.paymentsEnabled?payments.rows:[],aiConversations:conversations.rows}; }
async function updateAdminCustomer(id,data,user){const current=await getAdminCustomer(id);const {rows}=await getPool().query('UPDATE users SET name=COALESCE($2,name),email=COALESCE(LOWER($3),email),mobile=COALESCE($4,mobile),status=COALESCE($5,status),updated_at=NOW() WHERE id=$1 RETURNING id',[current.userId,data.name,data.email,data.mobile,data.status]);await getPool().query('UPDATE customers SET company_name=COALESCE($2,company_name),payments_enabled=COALESCE($3,payments_enabled) WHERE id=$1',[id,data.companyName,data.paymentsEnabled]);await audit(user.id,'customer.update','customer',id,data);return getAdminCustomer(id);}
async function disableAdminCustomer(id,user){const current=await getAdminCustomer(id);await getPool().query("UPDATE users SET status='disabled',updated_at=NOW() WHERE id=$1",[current.userId]);await audit(user.id,'customer.disable','customer',id,{});return {id:Number(id),status:'disabled'};}
async function dashboard() { const { rows } = await getPool().query(`SELECT (SELECT COUNT(*)::int FROM customers) customers,(SELECT COUNT(*)::int FROM orders WHERE created_at>=CURRENT_DATE-INTERVAL '30 days') AS "newOrders",(SELECT COUNT(*)::int FROM quotations WHERE status IS DISTINCT FROM 'approved') AS "pendingQuotations",(SELECT COUNT(*)::int FROM service_tickets WHERE status NOT IN ('closed','completed')) AS "activeServices",(SELECT COUNT(*)::int FROM technicians) technicians,(SELECT COUNT(*)::int FROM technician_jobs WHERE status='completed') AS "completedJobs",(SELECT COUNT(*)::int FROM technician_jobs WHERE status<>'completed') AS "pendingJobs",(SELECT COALESCE(SUM(final_amount),0) FROM quotations WHERE status='approved') revenue`); return rows[0]; }
async function report(type, query={}) { const supported = ['sales','orders','quotations','services','technicians','customers','products','locations','revenue','pending-jobs','completed-jobs','ai-leads','conversion-rate']; if (!supported.includes(type)) throw Object.assign(new Error('Unsupported report'), { status: 404 }); const summary=await dashboard();return { type,filters:{from:query.from||null,to:query.to||null},generatedAt:new Date().toISOString(),summary }; }
async function registerDeviceToken(userId, token, platform) { await getPool().query(`INSERT INTO device_tokens(user_id,token,platform,last_seen_at) VALUES($1,$2,$3,NOW()) ON CONFLICT(token) DO UPDATE SET user_id=EXCLUDED.user_id,platform=EXCLUDED.platform,last_seen_at=NOW(),active=TRUE`,[userId,token,platform]); }
async function notificationRecipients(audience) { const roles={customers:['customer'],technicians:['technician'],admins:['super_admin','admin','sales_manager','service_manager','technician_manager']};const params=[];let where="dt.active=TRUE AND u.status='active'";if(roles[audience]){params.push(roles[audience]);where+=' AND r.name=ANY($1)';}return (await getPool().query(`SELECT DISTINCT dt.token,u.id AS "userId" FROM device_tokens dt JOIN users u ON u.id=dt.user_id JOIN roles r ON r.id=u.role_id WHERE ${where}`,params)).rows; }
async function createBulkNotifications(recipients, message, user) { if(!recipients.length)return;const ids=[...new Set(recipients.map(row=>row.userId))];await getPool().query(`INSERT INTO notifications(user_id,channel,title,body) SELECT unnest($1::bigint[]),$2,$3,$4`,[ids,message.channel,message.title,message.body]);await audit(user.id,'notification.send','notification',null,{recipients:ids.length,title:message.title}); }
async function audit(userId, action, entityType, entityId, metadata) { await getPool().query('INSERT INTO audit_logs(user_id,action,entity_type,entity_id,metadata) VALUES($1,$2,$3,$4,$5::jsonb)', [userId, action, entityType, entityId, JSON.stringify(metadata)]); }
module.exports = { isConfigured, getPool, health, findUserByEmail, listCatalog, createCatalog, updateCatalog, deleteCatalog, listOrders, createOrder, getOrder, updateOrder, updateOrderStatus, listServices, createService, updateService, listJobs, updateJobStatus, calculatePrice, listAdminCustomers, createAdminCustomer, getAdminCustomer, updateAdminCustomer, disableAdminCustomer, dashboard, report, registerDeviceToken, notificationRecipients, createBulkNotifications };
