const database=require('../database'),firebase=require('./firebaseService');const pool=()=>database.getPool();
function interpolate(text,variables={}){return String(text||'').replace(/{{\s*([\w.]+)\s*}}/g,(_,key)=>variables[key]??`{{${key}}}`);}
async function email(user,title,body){if(!process.env.RESEND_API_KEY||!process.env.EMAIL_FROM)return{status:'skipped',error:'Email provider is not configured'};const response=await fetch('https://api.resend.com/emails',{method:'POST',headers:{Authorization:`Bearer ${process.env.RESEND_API_KEY}`,'Content-Type':'application/json'},body:JSON.stringify({from:process.env.EMAIL_FROM,to:[user.email],subject:title,text:body})});const result=await response.json();if(!response.ok)throw new Error(result.message||`Email provider returned ${response.status}`);return{status:'sent',providerId:result.id};}
async function sms(user,_title,body){if(!process.env.TWILIO_ACCOUNT_SID||!process.env.TWILIO_AUTH_TOKEN||!process.env.TWILIO_FROM_NUMBER)return{status:'skipped',error:'SMS provider is not configured'};if(!user.mobile)return{status:'skipped',error:'Recipient mobile is unavailable'};const auth=Buffer.from(`${process.env.TWILIO_ACCOUNT_SID}:${process.env.TWILIO_AUTH_TOKEN}`).toString('base64'),form=new URLSearchParams({To:user.mobile,From:process.env.TWILIO_FROM_NUMBER,Body:body}),response=await fetch(`https://api.twilio.com/2010-04-01/Accounts/${process.env.TWILIO_ACCOUNT_SID}/Messages.json`,{method:'POST',headers:{Authorization:`Basic ${auth}`,'Content-Type':'application/x-www-form-urlencoded'},body:form});const result=await response.json();if(!response.ok)throw new Error(result.message||`SMS provider returned ${response.status}`);return{status:'sent',providerId:result.sid};}
async function whatsapp(user,_title,body){const id=process.env.WHATSAPP_PHONE_NUMBER_ID,token=process.env.WHATSAPP_ACCESS_TOKEN;if(!id||!token)return{status:'skipped',error:'WhatsApp provider is not configured'};if(!user.mobile)return{status:'skipped',error:'Recipient mobile is unavailable'};const response=await fetch(`https://graph.facebook.com/${process.env.WHATSAPP_API_VERSION||'v23.0'}/${id}/messages`,{method:'POST',headers:{Authorization:`Bearer ${token}`,'Content-Type':'application/json'},body:JSON.stringify({messaging_product:'whatsapp',to:user.mobile.replace(/\D/g,''),type:'text',text:{body}})}),result=await response.json();if(!response.ok)throw new Error(result?.error?.message||`WhatsApp returned ${response.status}`);return{status:'sent',providerId:result.messages?.[0]?.id};}
async function log(userId,templateId,channel,title,body,result){await pool().query('INSERT INTO notification_deliveries(user_id,template_id,channel,title,body,status,provider_id,error_message,attempted_at) VALUES($1,$2,$3,$4,$5,$6,$7,$8,NOW())',[userId,templateId,channel,title,body,result.status,result.providerId,result.error]);if(result.status==='sent'||channel==='push')await pool().query('INSERT INTO notifications(user_id,channel,title,body) VALUES($1,$2,$3,$4)',[userId,channel,title,body]);}
async function send({users,template,channels,variables}){const title=interpolate(template.title,variables),body=interpolate(template.body,variables),results=[];for(const channel of channels){if(channel==='push'){const tokens=(await pool().query('SELECT token FROM device_tokens WHERE active AND user_id=ANY($1::bigint[])',[users.map(x=>x.id)])).rows.map(x=>x.token),r=await firebase.sendToTokens(tokens,{title,body},variables);for(const user of users)await log(user.id,template.id,'push',title,body,{status:r.configured?'sent':'skipped',error:r.configured?null:'Firebase is not configured'});results.push({channel,...r});continue;}for(const user of users){try{const r=await({email,sms,whatsapp}[channel])(user,title,body);await log(user.id,template.id,channel,title,body,r);results.push({channel,userId:user.id,...r});}catch(error){const r={status:'failed',error:error.message};await log(user.id,template.id,channel,title,body,r);results.push({channel,userId:user.id,...r});}}}return{recipients:users.length,results};}
function providerStatus(){return{push:firebase.isConfigured(),email:Boolean(process.env.RESEND_API_KEY&&process.env.EMAIL_FROM),sms:Boolean(process.env.TWILIO_ACCOUNT_SID&&process.env.TWILIO_AUTH_TOKEN&&process.env.TWILIO_FROM_NUMBER),whatsapp:Boolean(process.env.WHATSAPP_ACCESS_TOKEN&&process.env.WHATSAPP_PHONE_NUMBER_ID)};}
module.exports={send,providerStatus,interpolate};
