const bcrypt = require('bcryptjs');
const jwt = require('jsonwebtoken');
const database = require('../database');
const { jwtSecret,jwtIssuer,jwtAudience } = require('../config');
const crypto = require('crypto');

function issueToken(user) { const jti=crypto.randomUUID(); return jwt.sign(user,jwtSecret,{algorithm:'HS256',expiresIn:'8h',jwtid:jti,issuer:jwtIssuer,audience:jwtAudience}); }

async function login(req, res) {
  const email = req.body.email.trim().toLowerCase();
  const user = await database.findUserByEmail(email);
  if (!user || !(await bcrypt.compare(req.body.password, user.passwordHash))) return res.status(401).json({ error: 'Invalid credentials' });
  const adminRoles = ['super_admin', 'admin', 'sales_manager', 'service_manager', 'technician_manager', 'support_agent'];
  if (req.body.portal === 'admin' && !adminRoles.includes(user.role)) return res.status(403).json({ error: 'Admin access required' });
  if (req.body.portal && req.body.portal !== 'admin' && req.body.portal !== user.role) return res.status(403).json({ error: `${req.body.portal} access required` });
  const safeUser = { id: user.id, name: user.name, email: user.email, role: user.role };
  await database.getPool().query('INSERT INTO audit_logs(user_id,action,entity_type,metadata) VALUES($1,$2,$3,$4::jsonb)',[user.id,'auth.login','user',JSON.stringify({portal:req.body.portal||'unspecified',ip:req.ip})]);
  res.json({ token: issueToken(safeUser), user: safeUser });
}
function me(req, res) { res.json({ user: req.user }); }

async function register(req,res){const client=await database.getPool().connect();try{await client.query('BEGIN');const role=(await client.query("SELECT id FROM roles WHERE name='customer'")).rows[0];if(!role)throw Object.assign(new Error('Customer role is not configured'),{status:503});const hash=await bcrypt.hash(req.body.password,12);const {rows}=await client.query(`INSERT INTO users(role_id,name,email,mobile,password_hash,status) VALUES($1,$2,LOWER($3),$4,$5,'pending_verification') RETURNING id,name,email,mobile`,[role.id,req.body.name,req.body.email,req.body.mobile,hash]);const address={addressLine:req.body.address,city:req.body.city,state:req.body.state,pincode:req.body.pincode};const customer=(await client.query('INSERT INTO customers(user_id,company_name,address) VALUES($1,$2,$3::jsonb) RETURNING id',[rows[0].id,req.body.companyName,JSON.stringify(address)])).rows[0];await client.query(`INSERT INTO customer_addresses(customer_id,label,address_line,city,state,pincode,is_default) VALUES($1,'Primary',$2,$3,$4,$5,TRUE)`,[customer.id,req.body.address,req.body.city,req.body.state,req.body.pincode]);const otp=String(crypto.randomInt(100000,1000000));await client.query('INSERT INTO auth_otps(user_id,purpose,otp_hash,expires_at) VALUES($1,$2,$3,NOW()+INTERVAL \'10 minutes\')',[rows[0].id,'verify_registration',await bcrypt.hash(otp,10)]);await client.query('COMMIT');res.status(201).json({message:'Registration successful. Verify the OTP sent to your mobile/email.',verificationRequired:true,...(process.env.NODE_ENV==='production'?{}:{developmentOtp:otp})});}catch(e){await client.query('ROLLBACK');if(e.code==='23505')throw Object.assign(new Error('Email or mobile number is already registered'),{status:409});throw e;}finally{client.release();}}

async function createOtp(userId,purpose){const otp=String(crypto.randomInt(100000,1000000));await database.getPool().query('UPDATE auth_otps SET consumed_at=NOW() WHERE user_id=$1 AND purpose=$2 AND consumed_at IS NULL',[userId,purpose]);await database.getPool().query('INSERT INTO auth_otps(user_id,purpose,otp_hash,expires_at) VALUES($1,$2,$3,NOW()+INTERVAL \'10 minutes\')',[userId,purpose,await bcrypt.hash(otp,10)]);return otp;}
async function forgotPassword(req,res){const {rows}=await database.getPool().query('SELECT id FROM users WHERE LOWER(email)=LOWER($1) OR mobile=$1 LIMIT 1',[req.body.identifier]);let otp;if(rows[0])otp=await createOtp(rows[0].id,'reset_password');res.json({message:'If the account exists, a password reset OTP has been sent.',...(otp&&process.env.NODE_ENV!=='production'?{developmentOtp:otp}:{})});}
async function verifyOtp(req,res){const {rows:users}=await database.getPool().query('SELECT id,name,email FROM users WHERE LOWER(email)=LOWER($1) OR mobile=$1 LIMIT 1',[req.body.identifier]);if(!users[0])return res.status(422).json({error:'Invalid or expired OTP'});const {rows}=await database.getPool().query('SELECT id,otp_hash FROM auth_otps WHERE user_id=$1 AND purpose=$2 AND consumed_at IS NULL AND expires_at>NOW() AND attempts<5 ORDER BY id DESC LIMIT 1',[users[0].id,req.body.purpose]);if(!rows[0]||!await bcrypt.compare(req.body.otp,rows[0].otp_hash)){if(rows[0])await database.getPool().query('UPDATE auth_otps SET attempts=attempts+1 WHERE id=$1',[rows[0].id]);return res.status(422).json({error:'Invalid or expired OTP'});}await database.getPool().query('UPDATE auth_otps SET consumed_at=NOW() WHERE id=$1',[rows[0].id]);if(req.body.purpose==='verify_registration')await database.getPool().query("UPDATE users SET verified_at=NOW(),status='active',updated_at=NOW() WHERE id=$1",[users[0].id]);const resetToken=req.body.purpose==='reset_password'?jwt.sign({id:users[0].id,purpose:'password_reset'},jwtSecret,{expiresIn:'10m'}):undefined;res.json({verified:true,resetToken});}
async function resetPassword(req,res){let payload;try{payload=jwt.verify(req.body.resetToken,jwtSecret);}catch(_){return res.status(422).json({error:'Invalid or expired reset token'});}if(payload.purpose!=='password_reset')return res.status(422).json({error:'Invalid reset token'});await database.getPool().query('UPDATE users SET password_hash=$2,updated_at=NOW() WHERE id=$1',[payload.id,await bcrypt.hash(req.body.password,12)]);res.json({message:'Password reset successfully.'});}
async function logout(req,res){if(req.user.jti&&req.user.exp)await database.getPool().query('INSERT INTO revoked_tokens(jti,user_id,expires_at) VALUES($1,$2,to_timestamp($3)) ON CONFLICT DO NOTHING',[req.user.jti,req.user.id,req.user.exp]);res.json({message:'Logged out successfully.'});}
module.exports = { login, me, register, forgotPassword, verifyOtp, resetPassword, logout };
