import React, { useEffect, useState } from 'react';
import { ArrowLeft, Building2, Eye, Search, UserPlus, Users } from 'lucide-react';
import { get, patch, post, remove } from '../../api/client';
import StatusBadge from '../../components/ui/StatusBadge';

const fields = [['name', 'Full name'], ['email', 'Email', 'email'], ['mobile', 'Mobile'], ['companyName', 'Company'], ['password', 'Temporary password', 'password']];
export default function CustomersPage() {
  const [rows, setRows] = useState([]), [search, setSearch] = useState(''), [status, setStatus] = useState(''), [editing, setEditing] = useState(null), [profile, setProfile] = useState(null), [error, setError] = useState(''), [loading, setLoading] = useState(true);
  async function load() { setLoading(true); try { const params = new URLSearchParams({ pageSize: '100' }); if (search.trim()) params.set('search', search.trim()); if (status) params.set('status', status); const result = await get(`/api/admin/customers?${params}`); setRows(result.data || []); setError(''); } catch (e) { setError(e.message); } finally { setLoading(false); } }
  useEffect(() => { load(); }, []);
  async function open(id) { try { setProfile(await get(`/api/admin/customers/${id}`)); } catch (e) { setError(e.message); } }
  async function save(e) { e.preventDefault(); const data = Object.fromEntries(new FormData(e.currentTarget)); data.paymentsEnabled = data.paymentsEnabled === 'on'; if (editing.id) { delete data.password; await patch(`/api/admin/customers/${editing.id}`, data); } else await post('/api/admin/customers', data); setEditing(null); await load(); }
  async function disable(row) { if (window.confirm(`Disable ${row.name}?`)) { await remove(`/api/admin/customers/${row.id}`); await load(); } }
  if (profile) return <CustomerProfile customer={profile} onBack={() => setProfile(null)} onEdit={() => { setEditing({ ...profile, companyName: profile.company }); setProfile(null); }} />;
  return <section className="content customers-page">
    <div className="headline"><div><p>CUSTOMER CRM</p><h1>Customers</h1><small>Add, search, filter, view and manage customer accounts.</small></div><button className="primary" onClick={() => setEditing({})}><UserPlus size={17} />Add customer</button></div>
    <div className="customer-toolbar card"><div className="admin-search"><Search size={18} /><input aria-label="Search customers" value={search} onChange={e => setSearch(e.target.value)} onKeyDown={e => e.key === 'Enter' && load()} placeholder="Name, email, mobile or company" /></div><select aria-label="Customer status" value={status} onChange={e => setStatus(e.target.value)}><option value="">All statuses</option><option value="active">Active</option><option value="disabled">Disabled</option></select><button className="outline" onClick={load}>Apply filters</button></div>
    {editing && <form className="customer-editor card" onSubmit={save}><div className="customer-editor-heading"><h2>{editing.id ? 'Edit customer' : 'Add customer'}</h2><p>{editing.id ? 'Update account and company information.' : 'Create a customer login and profile.'}</p></div><div className="customer-editor-grid">{fields.map(([name, label, type = 'text']) => editing.id && name === 'password' ? null : <label key={name}>{label}<input name={name} type={type} defaultValue={editing[name] || ''} required={['name', 'email'].includes(name) || (!editing.id && name === 'password')} /></label>)}<label>Account status<select name="status" defaultValue={editing.status || 'active'}><option value="active">Active</option><option value="disabled">Disabled</option></select></label><label className="customer-payment"><input name="paymentsEnabled" type="checkbox" defaultChecked={editing.paymentsEnabled} /><span><b>Payments enabled</b><small>Allow payments for approved quotations.</small></span></label></div><div className="customer-editor-actions"><button type="button" className="outline" onClick={() => setEditing(null)}>Cancel</button><button className="primary">{editing.id ? 'Save changes' : 'Create customer'}</button></div></form>}
    {error && <div className="auth-error">{error}</div>}
    <article className="tablecard card customer-list"><div className="customer-list-heading"><h2>Customer directory</h2><p>{loading ? 'Loading customers…' : `${rows.length} customer${rows.length === 1 ? '' : 's'} shown`}</p></div>{loading ? <div className="customer-empty">Loading customer records…</div> : rows.length === 0 ? <div className="customer-empty"><Users size={34} /><h3>No customers found</h3><p>Try clearing the filters or add your first customer.</p></div> : <div className="customer-table-wrap"><table><thead><tr><th>Customer</th><th>Company</th><th>Mobile</th><th>Status</th><th>Joined</th><th>Actions</th></tr></thead><tbody>{rows.map(row => <tr key={row.id}><td><b>{row.name}</b><small>{row.email}</small></td><td>{row.company || '—'}</td><td>{row.mobile || '—'}</td><td><StatusBadge>{row.status}</StatusBadge></td><td>{new Date(row.createdAt).toLocaleDateString('en-IN')}</td><td><span className="table-actions"><button className="outline" onClick={() => open(row.id)}><Eye size={15} />View</button><button className="outline" onClick={() => setEditing({ ...row, companyName: row.company })}>Edit</button><button className="danger" disabled={row.status === 'disabled'} onClick={() => disable(row)}>Disable</button></span></td></tr>)}</tbody></table></div>}</article>
  </section>;
}

function CustomerProfile({ customer, onBack, onEdit }) { const sections = [['Addresses', customer.addresses||[], ['label', 'addressLine', 'city', 'state', 'pincode']], ['Orders', customer.orders||[], ['orderNo', 'estimatedPrice', 'status', 'createdAt']], ['Quotations', customer.quotations||[], ['quotationNo', 'finalAmount', 'status', 'validUntil']], ['Service tickets', customer.services||[], ['ticketNo', 'category', 'description', 'status', 'createdAt']], ['Sign assets',customer.assets||[],['assetNo','details','warrantyUntil','createdAt']], ...(customer.paymentsEnabled ? [['Payments', customer.payments||[], ['amount', 'status', 'reference', 'createdAt']]] : []), ['AI conversations', customer.aiConversations||[], ['question', 'response', 'escalationStatus', 'createdAt']],['Relevant activity',customer.activity||[],['action','entityType','entityId','createdAt']]]; return <section className="content"><div className="headline"><div><button className="text-button" onClick={onBack}><ArrowLeft size={16} />Customers</button><h1>{customer.name}</h1><small>{customer.email} · <StatusBadge>{customer.status}</StatusBadge></small></div><button className="primary" onClick={onEdit}>Edit customer</button></div><div className="customer-summary"><article className="card"><h2>Personal information</h2><p><b>Mobile</b><span>{customer.mobile || '—'}</span></p><p><b>Email</b><span>{customer.email}</span></p></article><article className="card"><Building2 /><h2>Company</h2><p>{customer.company || 'No company supplied'}</p><small>Payments {customer.paymentsEnabled ? 'enabled' : 'disabled'}</small></article></div>{sections.map(([title, items, keys]) => <article className="card profile-section" key={title}><h2>{title} <small>{items.length}</small></h2>{items.length ? <div className="profile-records">{items.map((item, i) => <div key={item.id || i}>{keys.map(key => <span key={key}><small>{key.replace(/([A-Z])/g, ' $1')}</small>{['amount', 'finalAmount', 'estimatedPrice'].includes(key) ? `₹${Number(item[key] || 0).toLocaleString('en-IN')}` : typeof item[key]==='object'?JSON.stringify(item[key]):String(item[key] ?? '—')}</span>)}</div>)}</div> : <p className="empty-copy">No records yet.</p>}</article>)}</section>; }
