import React, { useEffect, useState } from 'react';
import { ArrowUpRight, ClipboardList, Package, Plus, Users, Wrench, Zap } from 'lucide-react';
import { get } from '../../api/client';
import { useAuth } from '../../context/AuthContext';
import LoadingState from '../../components/ui/LoadingState';
import StatusBadge from '../../components/ui/StatusBadge';

export default function DashboardPage({ navigate }) {
  const { user } = useAuth();
  const [state,setState]=useState({dashboard:null,orders:[],services:[],leads:[]}),[loading,setLoading]=useState(true),[error,setError]=useState('');
  useEffect(()=>{let active=true;(async()=>{try{const [dashboard,orders,services,leads]=await Promise.all([get('/api/admin/dashboard'),get('/api/orders?limit=5'),get('/api/admin/operations/tickets'),get('/api/catalog/ai-leads?pageSize=100')]);if(active)setState({dashboard,orders:orders.data||[],services:(services.data||[]).slice(0,5),leads:leads.data||[]});}catch(e){if(active)setError(e.message)}finally{if(active)setLoading(false)}})();return()=>{active=false}},[]);
  if(loading)return <section className="overview-page"><LoadingState label="Loading live business overview…"/></section>;
  const data=state.dashboard||{},leadCounts=state.leads.reduce((counts,lead)=>({...counts,[lead.status]:(counts[lead.status]||0)+1}),{});
  const metrics=[['Customers',data.customers,Users,'blue'],['Orders',data.orders,Package,'purple'],['Quotations',data.quotations,ClipboardList,'orange'],['Service tickets',data.serviceTickets,Wrench,'red'],['Technicians',data.technicians,Users,'cyan'],['Revenue',`₹${Number(data.revenue||0).toLocaleString('en-IN')}`,ArrowUpRight,'green'],['Pending quotations',data.pendingQuotations,ClipboardList,'orange'],['Jobs',data.jobs,Wrench,'blue'],['AI leads',data.leads,Zap,'purple']];
  return <section className="overview-page">
    <div className="overview-heading"><div><p>{new Date().toLocaleDateString('en-IN',{weekday:'long',day:'numeric',month:'long',year:'numeric'})}</p><h1>Welcome, {user?.name||'Administrator'}</h1><small>Live operational data from the SignFix database.</small></div><div className="overview-actions"><button className="secondary-action" onClick={()=>navigate('/reports')}><ArrowUpRight size={17}/>Reports</button><button className="primary-action-button" onClick={()=>navigate('/orders')}><Plus size={18}/>View orders</button></div></div>
    {error&&<div className="auth-error">{error}</div>}
    <div className="overview-metrics">{metrics.map(([label,value,Icon,color])=><article key={label}><div className={`overview-metric-icon ${color}`}><Icon size={21}/></div><p>{label}</p><div><h2>{value??0}</h2></div></article>)}</div>
    <article className="overview-card recent-orders"><div className="overview-card-head"><div><h3>Recent orders</h3><p>Latest database records</p></div><button onClick={()=>navigate('/orders')}>View all orders →</button></div>{state.orders.length?<div className="overview-table-wrap"><table><thead><tr><th>ORDER ID</th><th>CUSTOMER</th><th>PRODUCT</th><th>ESTIMATE</th><th>STATUS</th><th>CREATED</th></tr></thead><tbody>{state.orders.map(order=><tr key={order.id}><td><b>{order.id}</b></td><td>{order.customer||order.createdBy}</td><td>{order.product||'—'}</td><td>₹{Number(order.estimatedPrice||0).toLocaleString('en-IN')}</td><td><StatusBadge>{order.status}</StatusBadge></td><td>{new Date(order.createdAt).toLocaleString('en-IN')}</td></tr>)}</tbody></table></div>:<div className="empty">No orders have been created.</div>}</article>
    <div className="overview-bottom-row"><article className="overview-card priority-services"><div className="overview-card-head"><div><h3>Recent service tickets</h3><p>Latest service activity</p></div><button onClick={()=>navigate('/services')}>View all →</button></div>{state.services.length?state.services.map(service=><div className="priority-row" key={service.id}><div className="service-tool"><Wrench size={18}/></div><div><b>{service.customer}</b><small>{service.id} · {service.category||service.issue}</small></div><StatusBadge>{service.priority}</StatusBadge><span>{service.technician||'Unassigned'}</span><StatusBadge>{service.status}</StatusBadge></div>):<div className="empty">No service tickets found.</div>}</article><article className="overview-card ai-leads"><div className="overview-card-head"><div><h3>AI sales leads</h3><p>Persisted lead pipeline</p></div><Zap/></div><h2>{state.leads.length} <small>total leads</small></h2><div className="lead-counts">{Object.entries(leadCounts).map(([status,count])=><span key={status}><b>{count}</b>{status.replaceAll('_',' ')}</span>)}</div>{!state.leads.length&&<div className="empty">No AI leads captured.</div>}<button onClick={()=>navigate('/ai-management')}>Review AI leads <ArrowUpRight size={16}/></button></article></div>
  </section>;
}
