import React,{useEffect,useState}from'react';
import{Bell,CheckCircle2,Edit3,Plus,Send,Smartphone}from'lucide-react';
import{get,patch,post,remove}from'../../api/client';
import{enablePush,firebaseConfigured}from'../../services/firebase';
import StatusBadge from'../../components/ui/StatusBadge';

const categories=['order','quotation','payment','service','technician','completion','promotion'];
const channels=[['push','Push notification'],['email','Email'],['sms','SMS'],['whatsapp','WhatsApp']];
export default function NotificationsPage(){
  const[templates,setTemplates]=useState([]),[deliveries,setDeliveries]=useState([]),[providers,setProviders]=useState({}),[editing,setEditing]=useState(null),[message,setMessage]=useState(''),[sending,setSending]=useState(false);
  async function load(){const[t,d,s]=await Promise.all([get('/api/notifications/templates'),get('/api/notifications/deliveries'),get('/api/notifications/status')]);setTemplates(t.data||[]);setDeliveries(d.data||[]);setProviders(s.providers||{});}
  useEffect(()=>{load().catch(e=>setMessage(e.message))},[]);
  async function activate(){try{await enablePush(()=>{});setMessage('Push notifications enabled on this device.')}catch(e){setMessage(e.message)}}
  async function saveTemplate(e){e.preventDefault();const f=new FormData(e.currentTarget),payload={name:f.get('name'),eventKey:f.get('eventKey'),category:f.get('category'),title:f.get('title'),body:f.get('body'),channels:channels.map(([id])=>id).filter(id=>f.get(id)==='on'),status:f.get('status')==='on'};editing.id?await patch(`/api/notifications/templates/${editing.id}`,payload):await post('/api/notifications/templates',payload);setEditing(null);await load()}
  async function disable(id){if(confirm('Disable this template?')){await remove(`/api/notifications/templates/${id}`);await load()}}
  async function dispatch(e){e.preventDefault();setSending(true);try{const f=new FormData(e.currentTarget),selected=templates.find(x=>String(x.id)===f.get('templateId')),variables={};for(const line of String(f.get('variables')||'').split('\n')){const i=line.indexOf('=');if(i>0)variables[line.slice(0,i).trim()]=line.slice(i+1).trim()}const selectedChannels=channels.map(([id])=>id).filter(id=>f.get(`send_${id}`)==='on');const result=await post('/api/notifications/dispatch',{templateId:Number(f.get('templateId')),audience:f.get('audience'),channels:selectedChannels.length?selectedChannels:selected?.channels,variables});setMessage(`Processed ${result.recipients} recipients across ${selectedChannels.length||selected?.channels?.length||0} channel(s).`);await load()}catch(e){setMessage(e.message)}finally{setSending(false)}}
  return <section className="content"><div className="headline"><div><p>COMMUNICATIONS</p><h1>Notification management</h1><small>Configure event templates and deliver through push, email, SMS or WhatsApp.</small></div><button className="outline" onClick={activate}><Smartphone size={17}/>Enable push here</button></div>
    <div className="provider-strip">{channels.map(([id,label])=><span className={providers[id]?'ready':'optional'} key={id}><i/>{label}<small>{providers[id]?'Configured':id==='push'&&!firebaseConfigured?'Client setup required':'Optional integration'}</small></span>)}</div>
    {message&&<p className="form-message">{message}</p>}
    <div className="notification-workspace"><article className="card template-panel"><div className="panel-heading"><div><h2>Notification templates</h2><p>Use placeholders such as <code>{'{{orderNo}}'}</code> and <code>{'{{status}}'}</code>.</p></div><button className="primary" onClick={()=>setEditing({category:'order',channels:['push'],status:true})}><Plus size={16}/>New template</button></div><div className="template-list">{templates.map(t=><div key={t.id}><span className={`template-icon ${t.category}`}><Bell size={16}/></span><div><b>{t.name}</b><small>{t.eventKey} · {(t.channels||[]).join(', ')}</small></div><StatusBadge>{t.category}</StatusBadge><button onClick={()=>setEditing(t)}><Edit3 size={15}/></button><button className="danger-link" onClick={()=>disable(t.id)}>Disable</button></div>)}</div></article>
      <form className="card admin-form" onSubmit={dispatch}><div className="section-title"><span className="feature-icon blue"><Send size={19}/></span><div><h2>Send from template</h2><p>Preview variables are substituted before delivery.</p></div></div><label>Template<select name="templateId" required>{templates.filter(x=>x.status).map(t=><option value={t.id} key={t.id}>{t.name}</option>)}</select></label><label>Audience<select name="audience"><option value="customers">Customers</option><option value="technicians">Technicians</option><option value="admins">Admin team</option><option value="all">Everyone</option></select></label><fieldset><legend>Override channels (optional)</legend>{channels.map(([id,label])=><label className="channel-check" key={id}><input type="checkbox" name={`send_${id}`}/>{label}</label>)}</fieldset><label>Template variables<textarea name="variables" rows="5" placeholder={'orderNo=SB-ORD-1001\nstatus=Ready'}/></label><button className="primary" disabled={sending}><Send size={16}/>{sending?'Sending…':'Send notification'}</button></form></div>
    <article className="tablecard card delivery-history"><div className="panel-heading"><div><h2>Delivery history</h2><p>Provider result for every recipient and channel.</p></div></div><table><thead><tr><th>Recipient</th><th>Channel</th><th>Title</th><th>Status</th><th>Details</th><th>Date</th></tr></thead><tbody>{deliveries.map(d=><tr key={d.id}><td>{d.email||'—'}</td><td>{d.channel}</td><td>{d.title}</td><td><StatusBadge>{d.status}</StatusBadge></td><td>{d.errorMessage||'Delivered'}</td><td>{new Date(d.createdAt).toLocaleString('en-IN')}</td></tr>)}</tbody></table></article>
    {editing&&<div className="area-modal-backdrop" onMouseDown={e=>e.target===e.currentTarget&&setEditing(null)}><div className="area-modal notification-template-modal"><div className="area-modal-head"><div><span><Bell size={19}/></span><div><h2>{editing.id?'Edit template':'New template'}</h2><p>Configure content, event and delivery channels.</p></div></div></div><form onSubmit={saveTemplate}><div className="area-form-grid"><label>Name<input name="name" defaultValue={editing.name||''} required/></label><label>Event key<input name="eventKey" defaultValue={editing.eventKey||''} placeholder="order.status" required/></label><label>Category<select name="category" defaultValue={editing.category}>{categories.map(x=><option key={x}>{x}</option>)}</select></label><label className="wide">Title<input name="title" defaultValue={editing.title||''} required/></label><label className="wide">Message body<textarea name="body" rows="6" defaultValue={editing.body||''} required/></label><fieldset className="wide"><legend>Channels</legend>{channels.map(([id,label])=><label className="channel-check" key={id}><input type="checkbox" name={id} defaultChecked={(editing.channels||[]).includes(id)}/>{label}</label>)}</fieldset><label className="channel-check"><input name="status" type="checkbox" defaultChecked={editing.status!==false}/>Active</label></div><div className="modal-actions"><button type="button" className="outline" onClick={()=>setEditing(null)}>Cancel</button><button className="primary">Save template</button></div></form></div></div>}
  </section>;
}
